# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hst.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thst.proto\x12\x06hstong\"X\n\x0e\x42\x61sicQotNotify\x12\"\n\x08security\x18\x01 \x01(\x0b\x32\x10.hstong.Security\x12\"\n\x08\x62\x61sicQot\x18\x02 \x01(\x0b\x32\x10.hstong.BasicQot\"O\n\x0e\x45xampleMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x14\n\x0c\x61notherValue\x18\x04 \x01(\x01\"*\n\x08Security\x12\x10\n\x08\x64\x61taType\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\xb5\x01\n\x08\x42\x61sicQot\x12\x11\n\topenPrice\x18\x01 \x01(\x01\x12\x11\n\thighPrice\x18\x02 \x01(\x01\x12\x10\n\x08lowPrice\x18\x03 \x01(\x01\x12\x11\n\tlastPrice\x18\x04 \x01(\x01\x12\x16\n\x0elastClosePrice\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x12\x12\x10\n\x08turnover\x18\x07 \x01(\x01\x12\x11\n\tamplitude\x18\x08 \x01(\x01\x12\x11\n\ttradeTime\x18\t \x01(\t\"\x8c\x01\n\rNotifyMessage\x12,\n\rnotifyMsgType\x18\x01 \x01(\x0e\x32\x15.hstong.NotifyMsgType\x12\x10\n\x08notifyId\x18\x02 \x01(\t\x12\x12\n\nnotifyTime\x18\x03 \x01(\x03\x12\'\n\x07payload\x18\x04 \x01(\x0b\x32\x16.hstong.BasicQotNotify*-\n\rNotifyMsgType\x12\x1c\n\x18TradeStockDeliverMsgType\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hst_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFYMSGTYPE._serialized_start=563
  _NOTIFYMSGTYPE._serialized_end=608
  _BASICQOTNOTIFY._serialized_start=21
  _BASICQOTNOTIFY._serialized_end=109
  _EXAMPLEMESSAGE._serialized_start=111
  _EXAMPLEMESSAGE._serialized_end=190
  _SECURITY._serialized_start=192
  _SECURITY._serialized_end=234
  _BASICQOT._serialized_start=237
  _BASICQOT._serialized_end=418
  _NOTIFYMESSAGE._serialized_start=421
  _NOTIFYMESSAGE._serialized_end=561
# @@protoc_insertion_point(module_scope)
